// Copyright (c) Microsoft. All rights reserved.
//
// Ported from ChatCompletions/Models/ChatCompletionChunk.cs.

import 'chat_completion_choice.dart';
import 'completion_usage.dart';

/// A streamed chunk of a chat-completion response.
class ChatCompletionChunk {
  /// Creates a [ChatCompletionChunk].
  const ChatCompletionChunk({
    required this.id,
    required this.created,
    required this.model,
    required this.choices,
    this.usage,
    this.serviceTier,
    this.systemFingerprint,
  });

  /// A unique identifier for the chat completion; the same for each chunk.
  final String id;

  /// The list of choice chunks.
  final List<ChatCompletionChoiceChunk> choices;

  /// The Unix timestamp (seconds) of when the completion was created.
  final int created;

  /// The model used to generate the completion.
  final String model;

  /// Usage statistics for the completion request.
  final CompletionUsage? usage;

  /// The service tier used for processing.
  final String? serviceTier;

  /// The backend configuration fingerprint.
  final String? systemFingerprint;

  /// The object type, always `chat.completion.chunk`.
  String get object => 'chat.completion.chunk';

  /// Serializes this chunk, omitting null fields.
  Map<String, dynamic> toJson() => {
    'id': id,
    'choices': choices.map((c) => c.toJson()).toList(),
    'object': object,
    'created': created,
    'model': model,
    if (usage != null) 'usage': usage!.toJson(),
    if (serviceTier != null) 'service_tier': serviceTier,
    if (systemFingerprint != null) 'system_fingerprint': systemFingerprint,
  };
}

/// A choice within a [ChatCompletionChunk].
class ChatCompletionChoiceChunk {
  /// Creates a [ChatCompletionChoiceChunk].
  const ChatCompletionChoiceChunk({
    required this.index,
    required this.delta,
    this.finishReason,
  });

  /// The index of the choice.
  final int index;

  /// The reason the model stopped generating tokens.
  final String? finishReason;

  /// The delta payload for this chunk.
  final ChatCompletionDelta delta;

  /// Serializes this choice chunk, omitting null fields.
  Map<String, dynamic> toJson() => {
    'index': index,
    if (finishReason != null) 'finish_reason': finishReason,
    'delta': delta.toJson(),
  };
}

/// The incremental delta payload of a chunk choice.
class ChatCompletionDelta {
  /// Creates a [ChatCompletionDelta].
  ChatCompletionDelta({
    this.content,
    this.refusal,
    this.role,
    this.functionCall,
    this.toolCalls,
  });

  /// The contents of the chunk message.
  final String? content;

  /// The refusal message generated by the model.
  final String? refusal;

  /// The role of the message author.
  String? role;

  /// Deprecated function-call output.
  ChoiceMessageFunctionCall? functionCall;

  /// Tool calls generated by the model.
  List<ChoiceMessageToolCall>? toolCalls;

  /// Serializes this delta. `content`/`refusal`/`role` always appear (nullable);
  /// `function_call`/`tool_calls` are omitted when null.
  Map<String, dynamic> toJson() => {
    'content': content,
    'refusal': refusal,
    'role': role,
    if (functionCall != null) 'function_call': functionCall!.toJson(),
    if (toolCalls != null)
      'tool_calls': toolCalls!.map((t) => t.toJson()).toList(),
  };
}
