// Copyright (c) Microsoft. All rights reserved.
//
// Ported from ChatCompletions/Models/ChatCompletionChoice.cs.

/// A choice in a chat-completion response.
class ChatCompletionChoice {
  /// Creates a [ChatCompletionChoice].
  const ChatCompletionChoice({
    required this.index,
    required this.message,
    this.finishReason,
  });

  /// The index of the choice.
  final int index;

  /// The reason the model stopped generating tokens.
  final String? finishReason;

  /// The generated message.
  final ChoiceMessage message;

  /// Serializes this choice, omitting null fields.
  Map<String, dynamic> toJson() => {
    'index': index,
    if (finishReason != null) 'finish_reason': finishReason,
    'message': message.toJson(),
  };
}

/// A chat-completion message generated by the model.
class ChoiceMessage {
  /// Creates a [ChoiceMessage].
  ChoiceMessage({
    this.role,
    this.annotations,
    this.content,
    this.refusal,
    this.audio,
    this.functionCall,
    this.toolCalls,
  });

  /// The role of the message author.
  String? role;

  /// Annotations for this message (for example web-search citations).
  List<ChoiceMessageAnnotation>? annotations;

  /// The text contents of the message.
  String? content;

  /// The refusal message generated by the model.
  String? refusal;

  /// Audio output data, when the audio modality is requested.
  ChoiceMessageAudio? audio;

  /// Deprecated function-call output.
  ChoiceMessageFunctionCall? functionCall;

  /// Tool calls generated by the model.
  List<ChoiceMessageToolCall>? toolCalls;

  /// Serializes this message, omitting null fields.
  Map<String, dynamic> toJson() => {
    if (role != null) 'role': role,
    if (annotations != null)
      'annotations': annotations!.map((a) => a.toJson()).toList(),
    if (content != null) 'content': content,
    if (refusal != null) 'refusal': refusal,
    if (audio != null) 'audio': audio!.toJson(),
    if (functionCall != null) 'function_call': functionCall!.toJson(),
    if (toolCalls != null)
      'tool_calls': toolCalls!.map((t) => t.toJson()).toList(),
  };
}

/// Audio output data in a chat-completion message.
class ChoiceMessageAudio {
  /// Creates a [ChoiceMessageAudio].
  const ChoiceMessageAudio({
    this.data,
    this.expiresAt = 0,
    this.id,
    this.transcript,
  });

  /// Base64-encoded audio bytes.
  final String? data;

  /// Unix timestamp after which the audio is no longer accessible.
  final int expiresAt;

  /// Unique identifier for this audio response.
  final String? id;

  /// Transcript of the generated audio.
  final String? transcript;

  /// Serializes this audio output, omitting null fields.
  Map<String, dynamic> toJson() => {
    'data': data,
    'expires_at': expiresAt,
    if (id != null) 'id': id,
    if (transcript != null) 'transcript': transcript,
  };
}

/// Deprecated function-call output.
class ChoiceMessageFunctionCall {
  /// Creates a [ChoiceMessageFunctionCall].
  const ChoiceMessageFunctionCall({this.name, this.arguments});

  /// The name of the function to call.
  final String? name;

  /// The arguments to call the function with, as a JSON string.
  final String? arguments;

  /// Serializes this function call, omitting null fields.
  Map<String, dynamic> toJson() => {
    if (name != null) 'name': name,
    if (arguments != null) 'arguments': arguments,
  };
}

/// A tool call generated by the model.
class ChoiceMessageToolCall {
  /// Creates a [ChoiceMessageToolCall].
  const ChoiceMessageToolCall({this.id, this.function});

  /// The ID of the tool call.
  final String? id;

  /// The function the model called.
  final ChoiceMessageFunctionCall? function;

  /// The tool type, always `function`.
  String get type => 'function';

  /// Serializes this tool call, omitting null fields.
  Map<String, dynamic> toJson() => {
    if (id != null) 'id': id,
    'type': type,
    if (function != null) 'function': function!.toJson(),
  };
}

/// An annotation for a message (web-search citation).
class ChoiceMessageAnnotation {
  /// Creates a [ChoiceMessageAnnotation].
  const ChoiceMessageAnnotation({required this.annotationUrlCitation});

  /// The URL citation details.
  final AnnotationUrlCitation annotationUrlCitation;

  /// The annotation type, always `url_citation`.
  String get type => 'url_citation';

  /// Serializes this annotation.
  Map<String, dynamic> toJson() => {
    'type': type,
    'url_citation': annotationUrlCitation.toJson(),
  };
}

/// A citation to a URL for a web-search result.
class AnnotationUrlCitation {
  /// Creates an [AnnotationUrlCitation].
  const AnnotationUrlCitation({
    this.endIndex,
    this.startIndex,
    this.title,
    this.url,
  });

  /// The character index where the citation ends.
  final int? endIndex;

  /// The character index where the citation starts.
  final int? startIndex;

  /// The title of the cited resource.
  final String? title;

  /// The URL of the cited resource.
  final String? url;

  /// Serializes this citation.
  Map<String, dynamic> toJson() => {
    'end_index': endIndex,
    'start_index': startIndex,
    'title': title,
    'url': url,
  };
}
