// Copyright (c) Microsoft. All rights reserved.
//
// Ported from ChatCompletions/Models/CompletionUsage.cs.

/// Usage statistics for a chat-completion request.
class CompletionUsage {
  /// Creates a [CompletionUsage].
  const CompletionUsage({
    required this.completionTokensDetails,
    required this.promptTokensDetails,
    this.completionTokens,
    this.promptTokens,
    this.totalTokens,
  });

  /// A zero-valued usage record.
  static const CompletionUsage zero = CompletionUsage(
    completionTokens: 0,
    promptTokens: 0,
    totalTokens: 0,
    completionTokensDetails: CompletionTokensDetails(),
    promptTokensDetails: PromptTokensDetails(),
  );

  /// Number of tokens in the generated completion.
  final int? completionTokens;

  /// Number of tokens in the prompt.
  final int? promptTokens;

  /// Total number of tokens used (prompt + completion).
  final int? totalTokens;

  /// Breakdown of tokens used in the completion.
  final CompletionTokensDetails completionTokensDetails;

  /// Breakdown of tokens used in the prompt.
  final PromptTokensDetails promptTokensDetails;

  /// Serializes this usage record.
  Map<String, dynamic> toJson() => {
    'completion_tokens': completionTokens,
    'prompt_tokens': promptTokens,
    'total_tokens': totalTokens,
    'completion_tokens_details': completionTokensDetails.toJson(),
    'prompt_tokens_details': promptTokensDetails.toJson(),
  };
}

/// Breakdown of tokens used in a completion.
class CompletionTokensDetails {
  /// Creates a [CompletionTokensDetails].
  const CompletionTokensDetails({
    this.acceptedPredictionTokens = 0,
    this.audioTokens = 0,
    this.reasoningTokens = 0,
    this.rejectedPredictionTokens = 0,
  });

  /// Accepted predicted-output tokens.
  final int acceptedPredictionTokens;

  /// Audio tokens generated by the model.
  final int audioTokens;

  /// Reasoning tokens generated by the model.
  final int reasoningTokens;

  /// Rejected predicted-output tokens.
  final int rejectedPredictionTokens;

  /// Serializes this breakdown.
  Map<String, dynamic> toJson() => {
    'accepted_prediction_tokens': acceptedPredictionTokens,
    'audio_tokens': audioTokens,
    'reasoning_tokens': reasoningTokens,
    'rejected_prediction_tokens': rejectedPredictionTokens,
  };
}

/// Breakdown of tokens used in the prompt.
class PromptTokensDetails {
  /// Creates a [PromptTokensDetails].
  const PromptTokensDetails({this.audioTokens = 0, this.cachedTokens = 0});

  /// Audio tokens present in the prompt.
  final int audioTokens;

  /// Cached tokens present in the prompt.
  final int cachedTokens;

  /// Serializes this breakdown.
  Map<String, dynamic> toJson() => {
    'audio_tokens': audioTokens,
    'cached_tokens': cachedTokens,
  };
}
