// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Parameters for an optional drafter (assistant) model that enables
/// speculative decoding.
///
/// The drafter proposes tokens cheaply and the main model verifies them, so
/// the output distribution is identical to decoding with the main model
/// alone — just faster when the drafter's guesses are accepted. Any GGUF
/// whose vocabulary matches the main model works (e.g. a Gemma 4 MTP
/// `*-assistant` drafter); this is not tied to one architecture.
class DraftModelOptions {
  DraftModelOptions({
    required this.modelPath,
    required this.gpuLayers,
    required this.maxDraftTokens,
  });

  /// Absolute filesystem path to the drafter `.gguf`.
  String modelPath;

  /// Number of drafter layers to offload to the GPU (`n_gpu_layers`).
  ///
  /// `0` forces CPU-only inference (e.g. the iOS Simulator).
  int gpuLayers;

  /// Maximum tokens drafted per verification step.
  int maxDraftTokens;

  List<Object?> _toList() {
    return <Object?>[
      modelPath,
      gpuLayers,
      maxDraftTokens,
    ];
  }

  Object encode() {
    return _toList();  }

  static DraftModelOptions decode(Object result) {
    result as List<Object?>;
    return DraftModelOptions(
      modelPath: result[0]! as String,
      gpuLayers: result[1]! as int,
      maxDraftTokens: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DraftModelOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(modelPath, other.modelPath) && _deepEquals(gpuLayers, other.gpuLayers) && _deepEquals(maxDraftTokens, other.maxDraftTokens);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Parameters for loading a GGUF model into a native llama.cpp session.
class ModelLoadRequest {
  ModelLoadRequest({
    required this.modelPath,
    required this.contextSize,
    required this.gpuLayers,
    this.mmprojPath,
    this.draftModel,
  });

  /// Absolute filesystem path to the `.gguf` model.
  String modelPath;

  /// Context window size (`n_ctx`).
  int contextSize;

  /// Number of layers to offload to the GPU (`n_gpu_layers`).
  ///
  /// `0` forces CPU-only inference (e.g. the iOS Simulator).
  int gpuLayers;

  /// Absolute path to the multimodal projector (`mmproj`) `.gguf`.
  ///
  /// When non-null the session also stands up an `mtmd` context, enabling
  /// image input via [GenerationRequest.images]. Null keeps the session
  /// text-only.
  String? mmprojPath;

  /// Optional drafter model enabling speculative decoding.
  ///
  /// Null disables speculation; the session then behaves exactly as a
  /// single-model session.
  DraftModelOptions? draftModel;

  List<Object?> _toList() {
    return <Object?>[
      modelPath,
      contextSize,
      gpuLayers,
      mmprojPath,
      draftModel,
    ];
  }

  Object encode() {
    return _toList();  }

  static ModelLoadRequest decode(Object result) {
    result as List<Object?>;
    return ModelLoadRequest(
      modelPath: result[0]! as String,
      contextSize: result[1]! as int,
      gpuLayers: result[2]! as int,
      mmprojPath: result[3] as String?,
      draftModel: result[4] as DraftModelOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ModelLoadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(modelPath, other.modelPath) && _deepEquals(contextSize, other.contextSize) && _deepEquals(gpuLayers, other.gpuLayers) && _deepEquals(mmprojPath, other.mmprojPath) && _deepEquals(draftModel, other.draftModel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Parameters for a single generation run against a loaded session.
class GenerationRequest {
  GenerationRequest({
    required this.sessionId,
    required this.prompt,
    required this.maxTokens,
    required this.temperature,
    this.topK,
    this.topP,
    this.seed,
    required this.stopSequences,
    this.images,
  });

  /// Session returned by [LlamaHostApi.loadModel].
  int sessionId;

  /// The fully formatted prompt to feed the model.
  String prompt;

  /// Hard cap on the number of tokens to generate.
  int maxTokens;

  /// Sampling temperature; `0` is greedy.
  double temperature;

  /// Top-k cutoff applied before temperature sampling. Null or `<= 0`
  /// disables the top-k stage.
  int? topK;

  /// Nucleus (top-p) cutoff applied before temperature sampling. Null or
  /// `>= 1.0` disables the top-p stage.
  double? topP;

  /// Sampler seed for reproducible generation. Null draws a random seed.
  int? seed;

  /// Strings that, when produced in the decoded output, halt generation.
  ///
  /// The matched stop sequence is removed from the streamed text and is not
  /// emitted. Matching runs against the decoded text (with special tokens
  /// rendered), so control markers such as Gemma's `<turn|>` work directly.
  /// Empty disables stop-sequence handling.
  List<String> stopSequences;

  /// Encoded image bytes (PNG/JPEG) to feed alongside [prompt].
  ///
  /// Each entry corresponds, in order, to one media marker in [prompt]. Only
  /// honoured when the session was loaded with a
  /// [ModelLoadRequest.mmprojPath]; otherwise ignored. Null or empty runs a
  /// text-only generation.
  List<Uint8List>? images;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      prompt,
      maxTokens,
      temperature,
      topK,
      topP,
      seed,
      stopSequences,
      images,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenerationRequest decode(Object result) {
    result as List<Object?>;
    return GenerationRequest(
      sessionId: result[0]! as int,
      prompt: result[1]! as String,
      maxTokens: result[2]! as int,
      temperature: result[3]! as double,
      topK: result[4] as int?,
      topP: result[5] as double?,
      seed: result[6] as int?,
      stopSequences: (result[7]! as List<Object?>).cast<String>(),
      images: (result[8] as List<Object?>?)?.cast<Uint8List>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenerationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(prompt, other.prompt) && _deepEquals(maxTokens, other.maxTokens) && _deepEquals(temperature, other.temperature) && _deepEquals(topK, other.topK) && _deepEquals(topP, other.topP) && _deepEquals(seed, other.seed) && _deepEquals(stopSequences, other.stopSequences) && _deepEquals(images, other.images);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A single streamed generation event.
///
/// Emitted repeatedly with [text] set while tokens are produced, then once
/// more with [done] true. On failure [error] is set and [done] is true.
class TokenEvent {
  TokenEvent({
    required this.sessionId,
    this.text,
    required this.done,
    this.error,
  });

  int sessionId;

  String? text;

  bool done;

  String? error;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      text,
      done,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static TokenEvent decode(Object result) {
    result as List<Object?>;
    return TokenEvent(
      sessionId: result[0]! as int,
      text: result[1] as String?,
      done: result[2]! as bool,
      error: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TokenEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(text, other.text) && _deepEquals(done, other.done) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DraftModelOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ModelLoadRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is GenerationRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is TokenEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return DraftModelOptions.decode(readValue(buffer)!);
      case 130:
        return ModelLoadRequest.decode(readValue(buffer)!);
      case 131:
        return GenerationRequest.decode(readValue(buffer)!);
      case 132:
        return TokenEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Control surface implemented natively (Swift) and called from Dart.
class LlamaHostApi {
  /// Constructor for [LlamaHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LlamaHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Loads the model and returns an opaque session id.
  Future<int> loadModel(ModelLoadRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.loadModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Starts generation; tokens arrive on the [LlamaTokenStream] event channel.
  Future<void> startGeneration(GenerationRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.startGeneration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Requests cancellation of an in-flight generation for [sessionId].
  Future<void> cancelGeneration(int sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.cancelGeneration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Saves the session's KV-cache state (and its token ledger) to [path].
  ///
  /// Returns the number of tokens covered by the snapshot: positive on
  /// success, `0` when the session holds no reusable cache (no file is
  /// written). Runs on the session's serial queue, so it cannot interleave
  /// with generation.
  Future<int> saveSessionState(int sessionId, String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.saveSessionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Restores KV-cache state previously written by [saveSessionState].
  ///
  /// Replaces the session's current cache contents. Returns the number of
  /// tokens restored. Fails (throws) when the file is missing, corrupt, or
  /// was written by an incompatible model — the session is left with an
  /// empty cache in that case, so the next generation simply prefills from
  /// scratch.
  Future<int> loadSessionState(int sessionId, String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.loadSessionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Frees the model/context associated with [sessionId].
  Future<void> disposeSession(int sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.disposeSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Token stream delivered from native to Dart via an `EventChannel`.
///
/// A single stream multiplexes every session's tokens; each [TokenEvent]
/// carries its [TokenEvent.sessionId] so listeners can filter per session.
Stream<TokenEvent> streamTokens( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamTokensChannel =
      EventChannel('dev.flutter.pigeon.llama_flutter.LlamaTokenStream.streamTokens$instanceName', pigeonMethodCodec);
  return streamTokensChannel.receiveBroadcastStream().map((dynamic event) {
    return event as TokenEvent;
  });
}
    
