// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class LlamaError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "LlamaError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? LlamaError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Parameters for an optional drafter (assistant) model that enables
/// speculative decoding.
///
/// The drafter proposes tokens cheaply and the main model verifies them, so
/// the output distribution is identical to decoding with the main model
/// alone — just faster when the drafter's guesses are accepted. Any GGUF
/// whose vocabulary matches the main model works (e.g. a Gemma 4 MTP
/// `*-assistant` drafter); this is not tied to one architecture.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DraftModelOptions: Hashable {
  /// Absolute filesystem path to the drafter `.gguf`.
  var modelPath: String
  /// Number of drafter layers to offload to the GPU (`n_gpu_layers`).
  ///
  /// `0` forces CPU-only inference (e.g. the iOS Simulator).
  var gpuLayers: Int64
  /// Maximum tokens drafted per verification step.
  var maxDraftTokens: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DraftModelOptions? {
    let modelPath = pigeonVar_list[0] as! String
    let gpuLayers = pigeonVar_list[1] as! Int64
    let maxDraftTokens = pigeonVar_list[2] as! Int64

    return DraftModelOptions(
      modelPath: modelPath,
      gpuLayers: gpuLayers,
      maxDraftTokens: maxDraftTokens
    )
  }
  func toList() -> [Any?] {
    return [
      modelPath,
      gpuLayers,
      maxDraftTokens,
    ]
  }
  static func == (lhs: DraftModelOptions, rhs: DraftModelOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.modelPath, rhs.modelPath) && deepEqualsMessages(lhs.gpuLayers, rhs.gpuLayers) && deepEqualsMessages(lhs.maxDraftTokens, rhs.maxDraftTokens)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DraftModelOptions")
    deepHashMessages(value: modelPath, hasher: &hasher)
    deepHashMessages(value: gpuLayers, hasher: &hasher)
    deepHashMessages(value: maxDraftTokens, hasher: &hasher)
  }
}

/// Parameters for loading a GGUF model into a native llama.cpp session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelLoadRequest: Hashable {
  /// Absolute filesystem path to the `.gguf` model.
  var modelPath: String
  /// Context window size (`n_ctx`).
  var contextSize: Int64
  /// Number of layers to offload to the GPU (`n_gpu_layers`).
  ///
  /// `0` forces CPU-only inference (e.g. the iOS Simulator).
  var gpuLayers: Int64
  /// Absolute path to the multimodal projector (`mmproj`) `.gguf`.
  ///
  /// When non-null the session also stands up an `mtmd` context, enabling
  /// image input via [GenerationRequest.images]. Null keeps the session
  /// text-only.
  var mmprojPath: String? = nil
  /// Optional drafter model enabling speculative decoding.
  ///
  /// Null disables speculation; the session then behaves exactly as a
  /// single-model session.
  var draftModel: DraftModelOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelLoadRequest? {
    let modelPath = pigeonVar_list[0] as! String
    let contextSize = pigeonVar_list[1] as! Int64
    let gpuLayers = pigeonVar_list[2] as! Int64
    let mmprojPath: String? = nilOrValue(pigeonVar_list[3])
    let draftModel: DraftModelOptions? = nilOrValue(pigeonVar_list[4])

    return ModelLoadRequest(
      modelPath: modelPath,
      contextSize: contextSize,
      gpuLayers: gpuLayers,
      mmprojPath: mmprojPath,
      draftModel: draftModel
    )
  }
  func toList() -> [Any?] {
    return [
      modelPath,
      contextSize,
      gpuLayers,
      mmprojPath,
      draftModel,
    ]
  }
  static func == (lhs: ModelLoadRequest, rhs: ModelLoadRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.modelPath, rhs.modelPath) && deepEqualsMessages(lhs.contextSize, rhs.contextSize) && deepEqualsMessages(lhs.gpuLayers, rhs.gpuLayers) && deepEqualsMessages(lhs.mmprojPath, rhs.mmprojPath) && deepEqualsMessages(lhs.draftModel, rhs.draftModel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModelLoadRequest")
    deepHashMessages(value: modelPath, hasher: &hasher)
    deepHashMessages(value: contextSize, hasher: &hasher)
    deepHashMessages(value: gpuLayers, hasher: &hasher)
    deepHashMessages(value: mmprojPath, hasher: &hasher)
    deepHashMessages(value: draftModel, hasher: &hasher)
  }
}

/// Parameters for a single generation run against a loaded session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerationRequest: Hashable {
  /// Session returned by [LlamaHostApi.loadModel].
  var sessionId: Int64
  /// The fully formatted prompt to feed the model.
  var prompt: String
  /// Hard cap on the number of tokens to generate.
  var maxTokens: Int64
  /// Sampling temperature; `0` is greedy.
  var temperature: Double
  /// Top-k cutoff applied before temperature sampling. Null or `<= 0`
  /// disables the top-k stage.
  var topK: Int64? = nil
  /// Nucleus (top-p) cutoff applied before temperature sampling. Null or
  /// `>= 1.0` disables the top-p stage.
  var topP: Double? = nil
  /// Sampler seed for reproducible generation. Null draws a random seed.
  var seed: Int64? = nil
  /// Strings that, when produced in the decoded output, halt generation.
  ///
  /// The matched stop sequence is removed from the streamed text and is not
  /// emitted. Matching runs against the decoded text (with special tokens
  /// rendered), so control markers such as Gemma's `<turn|>` work directly.
  /// Empty disables stop-sequence handling.
  var stopSequences: [String]
  /// Encoded image bytes (PNG/JPEG) to feed alongside [prompt].
  ///
  /// Each entry corresponds, in order, to one media marker in [prompt]. Only
  /// honoured when the session was loaded with a
  /// [ModelLoadRequest.mmprojPath]; otherwise ignored. Null or empty runs a
  /// text-only generation.
  var images: [FlutterStandardTypedData]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerationRequest? {
    let sessionId = pigeonVar_list[0] as! Int64
    let prompt = pigeonVar_list[1] as! String
    let maxTokens = pigeonVar_list[2] as! Int64
    let temperature = pigeonVar_list[3] as! Double
    let topK: Int64? = nilOrValue(pigeonVar_list[4])
    let topP: Double? = nilOrValue(pigeonVar_list[5])
    let seed: Int64? = nilOrValue(pigeonVar_list[6])
    let stopSequences = pigeonVar_list[7] as! [String]
    let images: [FlutterStandardTypedData]? = nilOrValue(pigeonVar_list[8])

    return GenerationRequest(
      sessionId: sessionId,
      prompt: prompt,
      maxTokens: maxTokens,
      temperature: temperature,
      topK: topK,
      topP: topP,
      seed: seed,
      stopSequences: stopSequences,
      images: images
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      prompt,
      maxTokens,
      temperature,
      topK,
      topP,
      seed,
      stopSequences,
      images,
    ]
  }
  static func == (lhs: GenerationRequest, rhs: GenerationRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.sessionId, rhs.sessionId) && deepEqualsMessages(lhs.prompt, rhs.prompt) && deepEqualsMessages(lhs.maxTokens, rhs.maxTokens) && deepEqualsMessages(lhs.temperature, rhs.temperature) && deepEqualsMessages(lhs.topK, rhs.topK) && deepEqualsMessages(lhs.topP, rhs.topP) && deepEqualsMessages(lhs.seed, rhs.seed) && deepEqualsMessages(lhs.stopSequences, rhs.stopSequences) && deepEqualsMessages(lhs.images, rhs.images)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerationRequest")
    deepHashMessages(value: sessionId, hasher: &hasher)
    deepHashMessages(value: prompt, hasher: &hasher)
    deepHashMessages(value: maxTokens, hasher: &hasher)
    deepHashMessages(value: temperature, hasher: &hasher)
    deepHashMessages(value: topK, hasher: &hasher)
    deepHashMessages(value: topP, hasher: &hasher)
    deepHashMessages(value: seed, hasher: &hasher)
    deepHashMessages(value: stopSequences, hasher: &hasher)
    deepHashMessages(value: images, hasher: &hasher)
  }
}

/// A single streamed generation event.
///
/// Emitted repeatedly with [text] set while tokens are produced, then once
/// more with [done] true. On failure [error] is set and [done] is true.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TokenEvent: Hashable {
  var sessionId: Int64
  var text: String? = nil
  var done: Bool
  var error: String? = nil
  /// Number of prompt tokens fed to the model, set on the `done` event.
  var promptTokenCount: Int64? = nil
  /// Prompt tokens served from the reused KV-cache prefix, set on the
  /// `done` event.
  var cachedTokenCount: Int64? = nil
  /// Number of tokens generated, set on the `done` event.
  var generatedTokenCount: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TokenEvent? {
    let sessionId = pigeonVar_list[0] as! Int64
    let text: String? = nilOrValue(pigeonVar_list[1])
    let done = pigeonVar_list[2] as! Bool
    let error: String? = nilOrValue(pigeonVar_list[3])
    let promptTokenCount: Int64? = nilOrValue(pigeonVar_list[4])
    let cachedTokenCount: Int64? = nilOrValue(pigeonVar_list[5])
    let generatedTokenCount: Int64? = nilOrValue(pigeonVar_list[6])

    return TokenEvent(
      sessionId: sessionId,
      text: text,
      done: done,
      error: error,
      promptTokenCount: promptTokenCount,
      cachedTokenCount: cachedTokenCount,
      generatedTokenCount: generatedTokenCount
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      text,
      done,
      error,
      promptTokenCount,
      cachedTokenCount,
      generatedTokenCount,
    ]
  }
  static func == (lhs: TokenEvent, rhs: TokenEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.sessionId, rhs.sessionId) && deepEqualsMessages(lhs.text, rhs.text) && deepEqualsMessages(lhs.done, rhs.done) && deepEqualsMessages(lhs.error, rhs.error) && deepEqualsMessages(lhs.promptTokenCount, rhs.promptTokenCount) && deepEqualsMessages(lhs.cachedTokenCount, rhs.cachedTokenCount) && deepEqualsMessages(lhs.generatedTokenCount, rhs.generatedTokenCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TokenEvent")
    deepHashMessages(value: sessionId, hasher: &hasher)
    deepHashMessages(value: text, hasher: &hasher)
    deepHashMessages(value: done, hasher: &hasher)
    deepHashMessages(value: error, hasher: &hasher)
    deepHashMessages(value: promptTokenCount, hasher: &hasher)
    deepHashMessages(value: cachedTokenCount, hasher: &hasher)
    deepHashMessages(value: generatedTokenCount, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return DraftModelOptions.fromList(self.readValue() as! [Any?])
    case 130:
      return ModelLoadRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return GenerationRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return TokenEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DraftModelOptions {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ModelLoadRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? GenerationRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? TokenEvent {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Control surface implemented natively (Swift) and called from Dart.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LlamaHostApi {
  /// Loads the model and returns an opaque session id.
  func loadModel(request: ModelLoadRequest, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Starts generation; tokens arrive on the [LlamaTokenStream] event channel.
  func startGeneration(request: GenerationRequest) throws
  /// Requests cancellation of an in-flight generation for [sessionId].
  func cancelGeneration(sessionId: Int64) throws
  /// Saves the session's KV-cache state (and its token ledger) to [path].
  ///
  /// Returns the number of tokens covered by the snapshot: positive on
  /// success, `0` when the session holds no reusable cache (no file is
  /// written). Runs on the session's serial queue, so it cannot interleave
  /// with generation.
  func saveSessionState(sessionId: Int64, path: String, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Restores KV-cache state previously written by [saveSessionState].
  ///
  /// Replaces the session's current cache contents. Returns the number of
  /// tokens restored. Fails (throws) when the file is missing, corrupt, or
  /// was written by an incompatible model — the session is left with an
  /// empty cache in that case, so the next generation simply prefills from
  /// scratch.
  func loadSessionState(sessionId: Int64, path: String, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Frees the model/context associated with [sessionId].
  func disposeSession(sessionId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LlamaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LlamaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LlamaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Loads the model and returns an opaque session id.
    let loadModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.loadModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ModelLoadRequest
        api.loadModel(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadModelChannel.setMessageHandler(nil)
    }
    /// Starts generation; tokens arrive on the [LlamaTokenStream] event channel.
    let startGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.startGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startGenerationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GenerationRequest
        do {
          try api.startGeneration(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startGenerationChannel.setMessageHandler(nil)
    }
    /// Requests cancellation of an in-flight generation for [sessionId].
    let cancelGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.cancelGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelGenerationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        do {
          try api.cancelGeneration(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelGenerationChannel.setMessageHandler(nil)
    }
    /// Saves the session's KV-cache state (and its token ledger) to [path].
    ///
    /// Returns the number of tokens covered by the snapshot: positive on
    /// success, `0` when the session holds no reusable cache (no file is
    /// written). Runs on the session's serial queue, so it cannot interleave
    /// with generation.
    let saveSessionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.saveSessionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveSessionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let pathArg = args[1] as! String
        api.saveSessionState(sessionId: sessionIdArg, path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveSessionStateChannel.setMessageHandler(nil)
    }
    /// Restores KV-cache state previously written by [saveSessionState].
    ///
    /// Replaces the session's current cache contents. Returns the number of
    /// tokens restored. Fails (throws) when the file is missing, corrupt, or
    /// was written by an incompatible model — the session is left with an
    /// empty cache in that case, so the next generation simply prefills from
    /// scratch.
    let loadSessionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.loadSessionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadSessionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let pathArg = args[1] as! String
        api.loadSessionState(sessionId: sessionIdArg, path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadSessionStateChannel.setMessageHandler(nil)
    }
    /// Frees the model/context associated with [sessionId].
    let disposeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.disposeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        do {
          try api.disposeSession(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeSessionChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Token stream delivered from native to Dart via an `EventChannel`.
///
/// A single stream multiplexes every session's tokens; each [TokenEvent]
/// carries its [TokenEvent.sessionId] so listeners can filter per session.
class StreamTokensStreamHandler: PigeonEventChannelWrapper<TokenEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamTokensStreamHandler) {
    var channelName = "dev.flutter.pigeon.llama_flutter.LlamaTokenStream.streamTokens"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<TokenEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
