// Copyright 2024 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:extensions/ai.dart';
import 'package:extensions/system.dart';

import 'agent_scope.dart';

/// A single model call's token usage, attributed to its conversation,
/// session, and model.
class ChatUsageRecord {
  /// Creates a [ChatUsageRecord].
  const ChatUsageRecord({
    required this.timestamp,
    required this.modelId,
    required this.sourceId,
    required this.provider,
    this.conversationId,
    this.sessionId,
    this.inputTokenCount,
    this.outputTokenCount,
    this.totalTokenCount,
    this.cachedInputTokenCount,
    this.reasoningTokenCount,
  });

  /// When the model call completed.
  final DateTime timestamp;

  /// The conversation the call belonged to, when scoped.
  final String? conversationId;

  /// The session (model-context epoch) active when the call was made.
  final String? sessionId;

  /// The provider's model identifier.
  final String modelId;

  /// The configured model source the call went through.
  final String sourceId;

  /// The provider type name (for example `anthropic`, `localLlama`).
  final String provider;

  /// Prompt tokens sent to the model.
  final int? inputTokenCount;

  /// Completion tokens generated by the model.
  final int? outputTokenCount;

  /// Total tokens reported by the provider.
  final int? totalTokenCount;

  /// Input tokens served from the provider's cache.
  final int? cachedInputTokenCount;

  /// Tokens spent on reasoning/thinking.
  final int? reasoningTokenCount;

  /// Builds a record from [usage] with call attribution.
  factory ChatUsageRecord.fromUsage(
    UsageDetails usage, {
    required DateTime timestamp,
    required String modelId,
    required String sourceId,
    required String provider,
    String? conversationId,
    String? sessionId,
  }) => ChatUsageRecord(
    timestamp: timestamp,
    conversationId: conversationId,
    sessionId: sessionId,
    modelId: modelId,
    sourceId: sourceId,
    provider: provider,
    inputTokenCount: usage.inputTokenCount,
    outputTokenCount: usage.outputTokenCount,
    totalTokenCount: usage.totalTokenCount,
    cachedInputTokenCount: usage.cachedInputTokenCount,
    reasoningTokenCount: usage.reasoningTokenCount,
  );
}

/// Receives one [ChatUsageRecord] per completed model call.
///
/// Implementations decide durability: an app may persist records for a
/// usage ledger, keep them in memory, or discard them.
abstract class UsageRecordSink {
  /// Records a completed model call's usage.
  void record(ChatUsageRecord record);
}

/// A [ChatClient] decorator that reports each call's token usage to a
/// [UsageRecordSink] and surfaces it to upper layers as [UsageContent].
///
/// Streaming providers deliver usage on [ChatResponseUpdate.usage]; the
/// agent layer only propagates message `contents`, so this decorator appends
/// one final synthetic update carrying a [UsageContent] with the call's
/// usage. That content flows into the coalesced assistant message, giving
/// per-message token detail to both live UI and the persisted transcript.
class UsageTrackingChatClient extends DelegatingChatClient {
  /// Wraps [inner], reporting usage to [sink].
  ///
  /// [scope] attributes records to a conversation and session; when null,
  /// records carry model/provider identity only.
  UsageTrackingChatClient(
    super.inner, {
    required this.sink,
    required this.modelId,
    required this.sourceId,
    required this.provider,
    this.scope,
  });

  /// Where completed-call usage records are reported.
  final UsageRecordSink sink;

  /// The provider's model identifier for this client.
  final String modelId;

  /// The configured model source id for this client.
  final String sourceId;

  /// The provider type name for this client.
  final String provider;

  /// The conversation scope this client serves, when known.
  final AgentScope? scope;

  @override
  Future<ChatResponse> getResponse({
    required Iterable<ChatMessage> messages,
    ChatOptions? options,
    CancellationToken? cancellationToken,
  }) async {
    final response = await super.getResponse(
      messages: messages,
      options: options,
      cancellationToken: cancellationToken,
    );
    final usage = response.usage;
    if (usage != null) {
      _record(usage);
      final last = response.messages.isEmpty ? null : response.messages.last;
      if (last != null && !_hasUsageContent(last.contents)) {
        last.contents.add(UsageContent(_cloneUsage(usage)));
      }
    }
    return response;
  }

  @override
  Stream<ChatResponseUpdate> getStreamingResponse({
    required Iterable<ChatMessage> messages,
    ChatOptions? options,
    CancellationToken? cancellationToken,
  }) async* {
    UsageDetails? latestUsage;
    UsageDetails? contentUsage;
    String? lastMessageId;
    await for (final update in super.getStreamingResponse(
      messages: messages,
      options: options,
      cancellationToken: cancellationToken,
    )) {
      // Providers report usage on updates cumulatively or as a single final
      // value; `toChatResponse` folds them last-wins, so mirror that here.
      if (update.usage != null) latestUsage = update.usage;
      for (final content in update.contents.whereType<UsageContent>()) {
        (contentUsage ??= UsageDetails()).add(content.details);
      }
      lastMessageId = update.messageId ?? lastMessageId;
      yield update;
    }
    // Prefer the update channel; fall back to UsageContent a provider may
    // have emitted instead. Never combine both (double counting).
    final usage = latestUsage ?? contentUsage;
    if (usage == null) return;
    _record(usage);
    if (contentUsage == null) {
      yield ChatResponseUpdate(
        role: ChatRole.assistant,
        messageId: lastMessageId,
        modelId: modelId,
        contents: [UsageContent(_cloneUsage(usage))],
      );
    }
  }

  void _record(UsageDetails usage) {
    sink.record(
      ChatUsageRecord.fromUsage(
        usage,
        timestamp: DateTime.now(),
        modelId: modelId,
        sourceId: sourceId,
        provider: provider,
        conversationId: scope?.conversationId,
        sessionId: scope?.sessionIdResolver(),
      ),
    );
  }

  static bool _hasUsageContent(List<AIContent>? contents) =>
      contents?.any((c) => c is UsageContent) ?? false;

  /// Copies [usage] so the injected content cannot be mutated by later
  /// accumulation against the original instance.
  static UsageDetails _cloneUsage(UsageDetails usage) => UsageDetails(
    inputTokenCount: usage.inputTokenCount,
    outputTokenCount: usage.outputTokenCount,
    totalTokenCount: usage.totalTokenCount,
    cachedInputTokenCount: usage.cachedInputTokenCount,
    reasoningTokenCount: usage.reasoningTokenCount,
    additionalCounts: usage.additionalCounts == null
        ? null
        : Map.of(usage.additionalCounts!),
  );
}
