import 'turn_token.dart';

/// Configuration options hosting AI Agents as an Executor.
class AIAgentHostOptions {
  AIAgentHostOptions();

  /// Gets or sets a value indicating whether agent streaming update events
  /// should be emitted during execution. If `null`, the value will be taken
  /// from the [TurnToken]
  bool? emitAgentUpdateEvents;

  /// Gets or sets a value indicating whether aggregated agent response events
  /// should be emitted during execution.
  bool emitAgentResponseEvents = true;

  /// Gets or sets a value indicating whether [ToolApprovalRequestContent]
  /// should be intercepted and sent as a message to the workflow for handling,
  /// instead of being raised as a request.
  bool interceptUserInputRequests = false;

  /// Gets or sets a value indicating whether [FunctionCallContent] without a
  /// corresponding [FunctionResultContent] should be intercepted and sent as a
  /// message to the workflow for handling, instead of being raised as a
  /// request.
  bool interceptUnterminatedFunctionCalls = false;

  /// Gets or sets a value indicating whether other messages from other agents
  /// should be assigned to the [User] role during execution.
  bool reassignOtherAgentsAsUsers = true;

  /// Gets or sets a value indicating whether incoming messages are
  /// automatically forwarded before new messages generated by the agent during
  /// its turn.
  bool forwardIncomingMessages = true;
}
